const SOCKET_TYPE = {
  'GET_ALL': 'GET_ALL',
  'SAVE_ONE': 'SAVE_ONE',
  'SAVE_ALL': 'SAVE_ALL',
  'UPDATE_ONE': 'UPDATE_ONE',
  'UPDATE_BATCH': 'UPDATE_BATCH',
  'DELETE_ONE': 'DELETE_ONE',
  'DELETE_BATCH': 'DELETE_BATCH',
  'ADD_ONE': 'ADD_ONE',
  'MESSAGE_TIP': 'MESSAGE_TIP'
}

module.exports = SOCKET_TYPE
